"""cli/product.py — veya 产品化入口 (init / start / doctor)。

把「框架」变成「产品」的最小闭环:
  veya init    首次运行向导: 接模型 → 选工作目录 → 生成开箱配置 → 给示例任务
  veya start   一键启动本地服务 (HTTP + SSE), 自动打开浏览器
  veya doctor  环境自检: 版本 / Key / 本地模型 / 工作区 / 端口

配置落点 (与 config.loader 消费路径一致):
  ~/.veya/config.json   主配置 (loader._default_paths 第 2 优先)
  ~/.veya/.env          API Key 文件 (chmod 600, 不落盘明文于仓库)
  工作区 .env           用户可见/可编辑的 Key 副本 (loader 读 cwd .env)
  工作区 .veya/security.yaml  安全策略 (allowed_paths 绑定工作区)
"""

from __future__ import annotations

import contextlib
import getpass
import json
import os
import sys
import webbrowser
from pathlib import Path
from typing import Any

_HOME_DIR = Path.home() / ".veya"
_CONFIG_PATH = _HOME_DIR / "config.json"
_ENV_PATH = _HOME_DIR / ".env"

PROVIDERS: dict[str, dict[str, str]] = {
    "openai": {"name": "OpenAI", "env": "OPENAI_API_KEY", "model": "gpt-4o-mini"},
    "anthropic": {"name": "Anthropic", "env": "ANTHROPIC_API_KEY", "model": "claude-sonnet-4-20250514"},
    "dashscope": {"name": "阿里云 DashScope", "env": "DASHSCOPE_API_KEY", "model": "qwen-plus"},
    "deepseek": {"name": "DeepSeek", "env": "DEEPSEEK_API_KEY", "model": "deepseek-chat"},
    "ollama": {"name": "Ollama (本地)", "env": "", "model": None},
}

OLLAMA_BASE = "http://localhost:11434"
OLLAMA_ENDPOINT = f"{OLLAMA_BASE}/v1/chat/completions"

SECURITY_TEMPLATE = """\
# Security policy generated by `veya init` — edit freely.
# 危险操作(写文件/外部 API/Shell)默认受限, 需要时在对话中确认或放宽此处。
default_permissions:
  - read_files
  - execute_code
  - network_connect

restricted_permissions:
  - write_files
  - call_external_api
  - shell_execute

audit_enabled: true
log_file: "security_audit.log"

whitelist:
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
    - "::1"
  allowed_paths:
    - "{workspace}"
    - "/tmp/"

blacklist:
  forbidden_patterns:
    - "../"
"""


# ---------------------------------------------------------------------------
# 本地模型探测 (Ollama)
# ---------------------------------------------------------------------------

def probe_ollama() -> list[str] | None:
    """探测本地 Ollama: 可达返回模型名列表, 否则 None。"""
    try:
        import urllib.request

        with urllib.request.urlopen(f"{OLLAMA_BASE}/api/tags", timeout=1.5) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        models = [m.get("name", "") for m in data.get("models", []) if m.get("name")]
        return models or []
    except Exception:
        return None


# ---------------------------------------------------------------------------
# 配置读写
# ---------------------------------------------------------------------------

def _load_config() -> dict[str, Any]:
    if _CONFIG_PATH.exists():
        try:
            return json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def _save_config(config: dict[str, Any]) -> None:
    _HOME_DIR.mkdir(parents=True, exist_ok=True)
    _CONFIG_PATH.write_text(
        json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def _write_env_file(path: Path, key: str, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    if path.exists():
        lines = path.read_text(encoding="utf-8").splitlines()
    lines = [ln for ln in lines if not ln.startswith(f"{key}=")]
    lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    with contextlib.suppress(OSError):
        os.chmod(path, 0o600)


# ---------------------------------------------------------------------------
# veya init
# ---------------------------------------------------------------------------

def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{prompt}{suffix}: ").strip()
    return raw or default


def _choose(prompt: str, options: list[str]) -> str:
    for i, opt in enumerate(options, 1):
        print(f"  {i}) {opt}")
    while True:
        raw = input(f"{prompt} (1-{len(options)}): ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1]
        print("  输入无效, 请重试。")


def run_init(argv: list[str]) -> int:
    """veya init — 首次运行向导 (支持全 flags 非交互)。"""
    import argparse

    p = argparse.ArgumentParser(prog="veya init", description="首次运行向导")
    p.add_argument("--provider", choices=list(PROVIDERS), help="模型提供商 (ollama=本地)")
    p.add_argument("--key", default=None, help="API Key (非交互模式)")
    p.add_argument("--model", default=None, help="模型名 (缺省用该提供商默认)")
    p.add_argument("--workspace", default=None, help="工作目录 (Agent 读写范围)")
    p.add_argument("--yes", action="store_true", help="非交互: 全部使用默认值/给定 flags")
    args = p.parse_args(argv)

    interactive = not args.yes

    print("=" * 56)
    print("  veya — 首次运行向导")
    print("  3 步接好: 模型 → 工作目录 → 直接开干")
    print("=" * 56)

    # ── 1. 模型 ──────────────────────────────────────────────────
    provider = args.provider
    if provider is None:
        print("\n[1/3] 选择模型提供商:")
        if interactive:
            options = list(PROVIDERS)
            provider = _choose("选择", options)
        else:
            provider = "openai"

    meta = PROVIDERS[provider]
    if provider == "ollama":
        models = probe_ollama()
        if models is None:
            print(
                f"\n⚠  未检测到本地 Ollama ({OLLAMA_BASE})。\n"
                "    请先安装并启动: https://ollama.com\n"
                "    完成后重新运行 `veya init` 或直接编辑 ~/.veya/config.json。"
            )
            if not interactive:
                print("    已跳过 (可在 config.json 中手动配置 VEYA_LLM_ENDPOINT)。")
        elif not models:
            print("\n⚠  Ollama 已启动但没有模型。请先: ollama pull qwen2.5:7b")
        else:
            print(f"\n✔  检测到本地 Ollama, 可用模型: {', '.join(models[:6])}")
        model = args.model or "qwen2.5:7b"
    else:
        print(f"\n[1/3] 提供商: {meta['name']} ({meta['env']})")
        model = args.model or meta["model"]

    # ── 2. API Key ───────────────────────────────────────────────
    key = args.key
    if provider != "ollama":
        if key is None:
            if interactive:
                key = getpass.getpass(f"  粘贴 {meta['env']} (输入为空则跳过, 用离线 stub): ")
            else:
                key = os.environ.get(meta["env"], "")
        if not key:
            print("  ⚠  未提供 Key — 将以离线 stub 模式运行 (仅体验流程, 不调用真实模型)。")

    # ── 3. 工作目录 ──────────────────────────────────────────────
    print("\n[2/3] 工作目录 (Agent 的文件读写与命令执行范围):")
    workspace = args.workspace
    if workspace is None:
        default_ws = str(Path.cwd())
        workspace = default_ws if not interactive else _ask("  输入工作目录", default_ws)
    ws = Path(workspace).expanduser().resolve()
    if not ws.is_dir():
        print(f"  ✗ 目录不存在: {ws}")
        return 1
    print(f"  ✔  工作区: {ws}")

    # ── 写入配置 ─────────────────────────────────────────────────
    config = _load_config()
    config.setdefault("llm", {})["provider"] = provider
    if model:
        config["llm"]["model"] = model
    if provider != "ollama" and key:
        config.setdefault("providers", {})[provider] = {"api_key": key}
    config["workspace"] = str(ws)
    config["persona"] = "build"
    _save_config(config)

    if provider != "ollama" and key:
        _write_env_file(_ENV_PATH, meta["env"], key)
        _write_env_file(ws / ".env", meta["env"], key)
        print(f"\n  ✔  Key 已写入 {_ENV_PATH} (chmod 600) 与 {ws / '.env'}")

    # 工作区安全策略
    sec_dir = ws / ".veya"
    sec_dir.mkdir(parents=True, exist_ok=True)
    sec_file = sec_dir / "security.yaml"
    if not sec_file.exists():
        sec_file.write_text(SECURITY_TEMPLATE.format(workspace=str(ws)), encoding="utf-8")
        print(f"  ✔  安全策略已生成: {sec_file} (危险操作默认受限, 可在对话中确认)")

    print("\n[3/3] 完成 ✔")
    print("\n下一步:")
    if provider == "ollama":
        print(f"  export VEYA_LLM_ENDPOINT={OLLAMA_ENDPOINT}")
        print("  (或写入工作区 .env: VEYA_LLM_ENDPOINT=http://localhost:11434/v1/chat/completions)")
    print("  veya start                 # 启动本地服务 + 打开浏览器")
    print('  veya "帮我把当前目录的 README 改得更产品化"   # 直接派任务')
    print('  或: veya-headless --agent plan --text "你的任务"')
    return 0


# ---------------------------------------------------------------------------
# veya start
# ---------------------------------------------------------------------------

def run_start(argv: list[str]) -> int:
    """veya start — 一键启动本地服务 (HTTP + SSE) 并打开浏览器。"""
    import argparse

    p = argparse.ArgumentParser(prog="veya start", description="一键启动本地服务")
    p.add_argument("--port", type=int, default=8765)
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--no-browser", action="store_true", help="不自动打开浏览器")
    p.add_argument("--open", action="store_true", help="显式打开浏览器 (默认自动)")
    args = p.parse_args(argv)

    url = f"http://{args.host}:{args.port}"
    print(f"veya 服务启动中 → {url}  (Ctrl-C 停止)")
    print(f"  API: {url}/api/v1/agent/stream (SSE)  健康检查: {url}/healthz")

    open_browser = not args.no_browser and sys.stdin.isatty()
    if args.open:
        open_browser = True
    if open_browser:
        with contextlib.suppress(Exception):
            webbrowser.open(url)

    from config.loader import load_config
    from server.assembly import Infra

    Infra.init(load_config())
    import uvicorn

    from veya.server.app import app

    uvicorn.run(app, host=args.host, port=args.port, log_level="info")
    return 0


# ---------------------------------------------------------------------------
# veya doctor
# ---------------------------------------------------------------------------

def run_doctor(argv: list[str]) -> int:
    """veya doctor — 环境自检 (可脚本化, 输出检查清单)。"""
    import argparse

    p = argparse.ArgumentParser(prog="veya doctor", description="环境自检")
    p.add_argument("--json", action="store_true", help="JSON 输出 (脚本友好)")
    args = p.parse_args(argv)

    import platform

    checks: list[dict[str, Any]] = []
    ok = True

    def add(name: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        checks.append({"name": name, "ok": bool(passed), "detail": detail})
        ok = ok and bool(passed)

    # Python / veya 版本
    py_ok = sys.version_info >= (3, 11)
    add("python>=3.11", py_ok, platform.python_version())
    try:
        import veya  # noqa: F401

        ver = "veya 0.6.0"
    except ImportError:
        ver = "未安装 (请 pip install veya)"
    add("veya 已安装", "veya 0.6.0" in ver or "not" not in ver, ver)

    # 配置
    cfg = _load_config()
    add("~/.veya/config.json", bool(cfg), str(_CONFIG_PATH) if cfg else "运行 `veya init` 生成")

    # 模型接入
    provider = (cfg.get("llm") or {}).get("provider", "")
    if provider == "ollama":
        models = probe_ollama()
        add("Ollama 本地模型", models is not None,
            f"{OLLAMA_BASE} → {', '.join(models[:4])}" if models else "不可达")
    elif provider:
        meta = PROVIDERS.get(provider)
        env = meta["env"] if meta else f"{provider.upper()}_API_KEY"
        key = (cfg.get("providers") or {}).get(provider, {}).get("api_key") if isinstance(
            (cfg.get("providers") or {}).get(provider), dict
        ) else ""
        key = key or os.environ.get(env, "")
        add(f"模型接入 ({provider})", bool(key),
            f"{env} 已配置" if key else f"未配置 {env} — 运行 `veya init` 或 export {env}")
    else:
        add("模型接入", False, "未配置 provider — 运行 `veya init`")

    # 工作区
    ws = cfg.get("workspace", "")
    ws_ok = bool(ws) and Path(ws).is_dir()
    add("工作区", ws_ok, ws if ws_ok else "未配置或目录不存在 — 运行 `veya init`")

    # 端口
    port_busy = _port_in_use(8765)
    add("端口 8765", not port_busy, "空闲" if not port_busy else "被占用 (veya start 可用 --port 换端口)")

    if args.json:
        print(json.dumps({"ok": ok, "checks": checks}, ensure_ascii=False, indent=2))
        return 0 if ok else 1

    print("veya doctor — 环境自检")
    for c in checks:
        mark = "✔" if c["ok"] else "✗"
        print(f"  {mark} {c['name']}: {c['detail']}")
    print(f"\n结论: {'一切就绪, 运行 `veya start` 开干' if ok else '有 N 项需处理, 按提示修复后重试'}"
          .replace("N", str(sum(1 for c in checks if not c["ok"]))))
    return 0 if ok else 1


def _port_in_use(port: int) -> bool:
    import socket

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.3)
        try:
            s.bind(("127.0.0.1", port))
            return False
        except OSError:
            return True


__all__ = ["PROVIDERS", "probe_ollama", "run_doctor", "run_init", "run_start"]
